language: rust
rust:
  - stable
script:
  - cargo build
  - cargo test
  - cargo web build --release
before_install:
  - sudo apt-get install -y libasound2-dev alsa alsa-utils
  - cargo install cargo-web